#include<iostream>
#include<conio.h>
using namespace std;

int main();
{
    char button;
    cout << "Input a Character." << endl;
    cin >> button;

    if(button == 'a')
    {
        cout << "\n Hello" << endl;
    }
    else if (button == 'b')
    {
        cout << "\n Namaste" << endl;
    }
    else if (button == 'c')
    {
        cout <<  "\n Salut" << endl;
    }
    else if (button == 'd')
    {
        cout << "\n Hola" << endl;
    }
    else if(bottun == 'e')
    {
        cout << "\n Ciao" << endl;
    }
    else
    {
        cout << "\n I am still Learning more" << endl;
    }
    getch()
    return 0;
}
