#include<iostream>
#include<stdio.h>
#include<conio.h>
using namespace std;

int BinaryToDecimal(int n)
{
    int ans = 0;
    int x = 1;
    while (n > 0)
    {
        int y = n%10;
        ans = ans +(x*y);
        x = x*2;
        n = n/10;
    }
    return ans;
}

int main()
{
    int n;
    cin >> n;

    cout <<  BinaryToDecimal(n) << endl;

    getch();
    return 0;
}
